### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by superguigui** [mattdesl/glsl-fxaa#1]
Hi !
I have this error on installation, 

```
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "i"
npm ERR! node v0.12.2
npm ERR! npm  v2.11.1
npm ERR! path /mypath/node_modules/glsl-fxaa/node_modules/glslify/node_modules/replace-method/node_modules/recast/node_modules/esprima/bin/esparse.js
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, chmod '/mypath/node_modules/glsl-fxaa/node_modules/glslify/node_modules/replace-method/node_modules/recast/node_modules/esprima/bin/esparse.js'
```

I'm guessing you have to update the glslify dependency to 2.2.1 in your package.json ?

Cheers,

**Comment by mattdesl** [comment]
Thanks, I'll update this package to use glslify@2.0. Working on it now :+1:

**Comment by mattdesl** [comment]
Ok, fixed everything, updated to glslify2, modernized the demo and cleaned code up. Pushed to 3.0.0. Also published to gh-pages:
http://mattdesl.github.io/glsl-fxaa/demo/

**Comment by superguigui** [comment]
That's awesome Matt thanks !

**Comment by mattdesl** [comment]
Just a heads up - eventually I plan to split this into two modules:

`glsl-fxaa` will just be a single function that targets the simplest use case
`glsl-shader-fxaa` will be a vertex / fragment shader "ready to go" with the most optimized version of this

This way both modules can be optimized and simplified. Right now it's a bit messy trying to support both use cases.

**Comment by superguigui** [comment]
So you mean you won't provide texcoords in `glsl-fxaa` ?
In most use case it's better to use the method without having to bother about `v_rgbNW`, `v_rgbNE` etc...

Here's how I use it in my current post-processing workflow (i was porting another fxaa implementation before I stumbled on yours that fitted right into how i wanted to use it). 

``` glsl
uniform sampler2D tInput;
uniform vec2 resolution;
uniform float time;
varying vec2 vUv;

#pragma glslify: vignette = require(./passes/vignette/vignette.frag)
#pragma glslify: brightness = require(./passes/brightness/brightness.frag)
#pragma glslify: contrast = require(./passes/contrast/contrast.frag)
#pragma glslify: film = require(./passes/film/film.frag)
#pragma glslify: fxaa = require(glsl-fxaa)

void main() {
  vec4 color = fxaa(tInput, vUv * resolution, resolution);
  color = vignette(color, 1.4, 2.3, resolution);
  color = brightness(color, 0.1);
  color = contrast(color, 0.68);
  color = film(color, vUv, time, 2048.0, 0.4, 0.3);

  gl_FragColor = color;
}
```

**Comment by mattdesl** [comment]
Yes the `v_rgbNW` stuff is annoying to use in practice. So most of the time it's easier just to use it like you are using there.

The "optimized" module would be used like this:

``` js
var vert = glslify('glsl-shader-fxaa/vert')
var frag = glslify('glsl-shader-fxaa/frag')
var fxaa = createShader(gl, vert, frag)
```

It wouldn't have all the weirdness of `out` function parameters so it would also be really easy to copy + paste if you want to inline it into your custom shaders for more optimization. (Or if you need a different setup for uniforms / vertex inputs).
